-- NODE7 public jobs used by node7-jobcenter.
-- These are automatically registered at runtime and can also be merged permanently into node7-core/shared/jobs.lua.
return {
    lumberjack = {
        name = 'lumberjack',
        label = 'Lumberjack',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Apprentice', payment = 5 },
            ['1'] = { name = 'Worker', payment = 7 },
            ['2'] = { name = 'Skilled Worker', payment = 9 },
            ['3'] = { name = 'Foreman', payment = 12 },
        },
    },
    miner = {
        name = 'miner',
        label = 'Miner',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Prospect', payment = 6 },
            ['1'] = { name = 'Miner', payment = 8 },
            ['2'] = { name = 'Experienced Miner', payment = 11 },
            ['3'] = { name = 'Pit Foreman', payment = 14 },
        },
    },
    farmer = {
        name = 'farmer',
        label = 'Farmer',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Farmhand', payment = 5 },
            ['1'] = { name = 'Field Worker', payment = 7 },
            ['2'] = { name = 'Experienced Farmer', payment = 9 },
            ['3'] = { name = 'Field Foreman', payment = 11 },
        },
    },
    ranchhand = {
        name = 'ranchhand',
        label = 'Ranch Hand',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'New Hand', payment = 5 },
            ['1'] = { name = 'Ranch Hand', payment = 7 },
            ['2'] = { name = 'Senior Hand', payment = 9 },
            ['3'] = { name = 'Ranch Foreman', payment = 12 },
        },
    },
    fisherman = {
        name = 'fisherman',
        label = 'Fisherman',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Deckhand', payment = 5 },
            ['1'] = { name = 'Fisherman', payment = 6 },
            ['2'] = { name = 'Experienced Fisherman', payment = 8 },
            ['3'] = { name = 'Fishing Foreman', payment = 10 },
        },
    },
    hunter = {
        name = 'hunter',
        label = 'Hunter',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Tracker', payment = 6 },
            ['1'] = { name = 'Hunter', payment = 8 },
            ['2'] = { name = 'Experienced Hunter', payment = 11 },
            ['3'] = { name = 'Master Hunter', payment = 14 },
        },
    },
    wagoner = {
        name = 'wagoner',
        label = 'Freight Wagoner',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Loader', payment = 7 },
            ['1'] = { name = 'Wagoner', payment = 9 },
            ['2'] = { name = 'Experienced Wagoner', payment = 12 },
            ['3'] = { name = 'Freight Foreman', payment = 15 },
        },
    },
    postal = {
        name = 'postal',
        label = 'Postal Courier',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Mail Runner', payment = 5 },
            ['1'] = { name = 'Courier', payment = 7 },
            ['2'] = { name = 'Senior Courier', payment = 9 },
            ['3'] = { name = 'Route Foreman', payment = 11 },
        },
    },
    stablehand = {
        name = 'stablehand',
        label = 'Stable Hand',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Stable Helper', payment = 4 },
            ['1'] = { name = 'Stable Hand', payment = 6 },
            ['2'] = { name = 'Senior Stable Hand', payment = 7 },
            ['3'] = { name = 'Stable Foreman', payment = 9 },
        },
    },
    townworker = {
        name = 'townworker',
        label = 'Town Worker',
        type = 'public',
        defaultDuty = true,
        offDutyPay = false,
        grades = {
            ['0'] = { name = 'Laborer', payment = 4 },
            ['1'] = { name = 'Town Worker', payment = 6 },
            ['2'] = { name = 'Senior Worker', payment = 8 },
            ['3'] = { name = 'Maintenance Foreman', payment = 10 },
        },
    },
}
